on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: linux316.unoeuro.com
        username: kollapollen.se
        password: ${{ secrets.FTP_PASSWORD }}  # Store your FTP password as a secret in your GitHub repository settings
        local-dir: ./  # Set this to the directory in your repo that you want to upload
        server-dir: /public_html/  # Set this to the target directory on your server
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          fileToExclude.txt
    env:
      FTP_PASSIVE: true  # Using passive mode, recommended for most FTP servers
